version: 2.1

jobs:
  build-app:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Restaurar dependencias App
          command: dotnet restore IW7PP.sln
      - run:
          name: Compilar App
          command: dotnet build App/IW7PP.csproj --configuration Release

  build-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Restaurar dependencias de Tests
          command: dotnet restore IW7PP.sln

  analyze-code:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Analizar estilo de código
          command: dotnet format IW7PP.sln --check

workflows:
  parallel-workflow:
    jobs:
      - build-app
      - build-tests
      - analyze-code
