version: 2.1

jobs:
  build-app:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Restaurar dependencias de la App
          command: dotnet restore App/App.csproj
      - run:
          name: Compilar la App
          command: dotnet build App/App.csproj --configuration Release

  build-libs:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Restaurar dependencias de las Librerías
          command: dotnet restore Libs/Libs.csproj
      - run:
          name: Compilar las Librerías
          command: dotnet build Libs/Libs.csproj --configuration Release

  analyze-code:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Analizar Código
          command: dotnet format --check

workflows:
  parallel-workflow:
    jobs:
      - build-app
      - build-libs
      - analyze-code
